import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowUpRight, Building2, Check, ChevronRight, FileText, GitBranch, LayoutDashboard, Upload, ShieldCheck } from 'lucide-react';
import './styles.css';

async function request(path, options) {
  const res = await fetch('/api' + path, options);
  const data = await res.json();
  if (!res.ok) throw new Error(typeof data.detail === 'string' ? data.detail : 'Please check your input and try again.');
  return data;
}
const post = (body) => ({method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body)});

function App() {
  const [tab,setTab] = useState('Overview');
  const [data,setData] = useState(null);
  const [error,setError] = useState('');
  const [notice,setNotice] = useState('');
  const [busy,setBusy] = useState(false);
  async function refresh() {
    const [project,summary,activities,reports,audit] = await Promise.all(['/project','/summary','/activities','/reports','/audit'].map(p=>request(p)));
    setData({project,summary,activities,reports,audit});
  }
  useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
  async function run(fn) { setBusy(true);setError('');setNotice('');try{await fn();await refresh();}catch(e){setError(e.message);}finally{setBusy(false);} }
  async function upload(e) { const file=e.target.files[0];if(!file)return;const body=new FormData();body.append('file',file);await run(async()=>{const result=await request('/schedules/validate',{method:'POST',body});setNotice(`${result.activities} activities checked. ${result.message}`);});e.target.value=''; }
  const pending=data?.reports.filter(r=>r.status==='pending') || [];
  const nav=[['Overview',LayoutDashboard],['Activities',Activity],['Report review',FileText],['Dependencies',GitBranch],['Audit trail',ShieldCheck]];
  return <div className="shell">
    <aside><a className="brand" href="/" aria-label="InfraSight home"><span className="brand-icon"><Building2 size={23}/></span>InfraSight<span className="ai">AI</span></a><div className="workspace-label">WORKSPACE</div><div className="workspace"><span className="initials">RI</span><div>Riverside project<small>Development workspace</small></div></div><nav>{nav.map(([name,Icon])=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><Icon size={18}/>{name}{name==='Report review'&&pending.length>0&&<b>{pending.length}</b>}</button>)}</nav><div className="sidebar-bottom"><span className="dot"/> Local development <small>v0.1 · Team starter</small></div></aside>
    <main><header><div>Workspace <ChevronRight size={14}/> Riverside Infrastructure</div><span className="avatar">IS</span></header><div className="content"><div className="page-heading"><div><div className="eyebrow">PROJECT INTELLIGENCE</div><h1>{tab==='Overview'?'Project overview':tab}</h1><p>A clear view of progress. A better view of what comes next.</p></div><label className={`upload ${busy?'disabled':''}`}><Upload size={16}/> Validate schedule<input aria-label="Validate schedule CSV" type="file" accept=".csv" disabled={busy} onChange={upload}/></label></div>
    <div className="demo"><span className="dot"/><strong>Demo workspace</strong><span>Synthetic data · 01 Oct 2026 baseline · AI predictions are not enabled</span></div>
    {error&&<div role="alert" className="error">{error} {!data&&<button onClick={()=>run(async()=>{})}>Retry connection</button>}</div>}{notice&&<div role="status" className="notice">{notice}</div>}
    {!data?<div className="panel">{error?'Start the backend on port 8000, then retry.':'Loading your project…'}</div>:<>
    {tab==='Overview'&&<><section className="stats">{[['Actual progress',`${data.summary.actual}%`,'Verified activity average'],['Planned progress',`${data.summary.planned}%`,'Sample baseline average'],['Behind schedule',data.summary.behind,'Activities below planned progress'],['Awaiting review',pending.length,'Reports requiring a decision']].map(([label,value,caption],i)=><article key={label}><div>{label}<ArrowUpRight size={17}/></div><strong className={i===2?'amber':''}>{value}</strong><small>{caption}</small></article>)}</section><div className="overview-grid"><section className="panel"><div className="section-title"><h2>Progress by activity</h2><span className="legend"><i/>Actual <i className="planned"/>Planned</span></div>{data.activities.map(a=><div className="chart-row" key={a.id}><div>{a.name}<span>{a.actual}% <small>/ {a.planned}%</small></span></div><div className="track"><div className="baseline" style={{width:`${a.planned}%`}}/><div className="actual" style={{width:`${a.actual}%`}}/></div></div>)}<p className="footnote">{data.summary.method}</p></section><section className="panel attention"><span className="eyebrow">NEXT ACTION</span><h2>Keep your progress<br/>grounded in evidence.</h2><p>{pending.length?`${pending.length} report is ready for review. Confirm the activity and progress before updating your project.`:'All reports have been reviewed. Add a site update to continue.'}</p><button className="primary" onClick={()=>setTab('Report review')}>Review reports <ChevronRight size={16}/></button><div className="attention-note"><ShieldCheck size={21}/><p>Every review is recorded.<small>Trace decisions back to the original report.</small></p></div></section></div></>}
    {(tab==='Overview'||tab==='Activities')&&<section className="panel"><div className="section-title"><h2>Activity register</h2><span className="muted">{data.activities.length} activities</span></div><div className="table-scroll"><table><thead><tr><th>Activity</th><th>Planned</th><th>Actual</th><th>Variance</th><th>Status</th></tr></thead><tbody>{data.activities.map(a=><tr key={a.id}><td><small className="activity-id">{a.id}</small>{a.name}</td><td>{a.planned}%</td><td>{a.actual}%</td><td>{a.variance>0?'+':''}{a.variance} pp</td><td><span className={`pill ${a.variance<0?'warning':''}`}>{a.variance<0?'Behind':a.actual===100?'Complete':a.variance>0?'Ahead':'On plan'}</span></td></tr>)}</tbody></table></div></section>}
    {tab==='Report review'&&<div className="review-grid"><section className="panel"><h2>Site reports</h2><p className="muted">Demo suggestions are fixtures, not model-generated matches.</p>{data.reports.map(r=><article className="report" key={r.id}><div className="section-title"><span className="activity-id">REPORT {r.id} · {r.reporting_date}</span><span className="pill">{r.status}</span></div><blockquote>{r.text}</blockquote><p><strong>{r.activity_id}</strong> · {data.activities.find(a=>a.id===r.activity_id)?.name}</p><p className="muted">Cumulative progress: {r.progress}% · {r.source}</p>{r.status==='pending'&&<div className="actions"><button disabled={busy} className="primary" onClick={()=>run(()=>request(`/reports/${r.id}/review`,post({action:'approve'})))}><Check size={16}/>Approve progress</button><button disabled={busy} onClick={()=>run(()=>request(`/reports/${r.id}/review`,post({action:'reject'})))}>Reject</button></div>}</article>)}</section><section className="panel"><h2>Add a manual report</h2><p className="muted">Choose the activity yourself until matching is integrated.</p><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);run(async()=>{await request('/reports',post({activity_id:f.get('activity_id'),text:f.get('text'),progress:Number(f.get('progress')),reporting_date:f.get('reporting_date')}));form.reset();setNotice('Report added to the review queue.');});}}><label>Activity<select name="activity_id">{data.activities.map(a=><option key={a.id} value={a.id}>{a.id} · {a.name}</option>)}</select></label><label>Reporting date<input name="reporting_date" type="date" required defaultValue="2026-10-01"/></label><label>Cumulative progress (%)<input name="progress" type="number" min="0" max="100" step="0.1" required/></label><label>Site update<textarea name="text" required maxLength="5000" rows="4"/></label><button className="primary" disabled={busy}>Submit for review</button></form></section></div>}
    {tab==='Dependencies'&&<section className="panel"><h2>Activity sequence</h2><p className="muted">Sample predecessor relationships. Critical-path and delay propagation calculations are planned.</p><div className="dependency-list">{data.activities.map(a=><div key={a.id}><span className="node-id">{a.id}</span><div><strong>{a.name}</strong><small>{a.predecessor?`Follows ${a.predecessor}`:'Start activity'} · {a.actual}% complete</small></div><span className={`pill ${a.variance<0?'warning':''}`}>{a.variance<0?'Behind':'On plan'}</span></div>)}</div></section>}
    {tab==='Audit trail'&&<section className="panel"><h2>Review history</h2>{data.audit.length?data.audit.map(a=><div className="audit-row" key={a.id}><ShieldCheck size={18}/><div><strong>Report {a.report_id} · {a.action}</strong><p>{a.details}</p></div></div>):<p className="muted">Review a report to create the first audit entry.</p>}</section>}
    </>}<footer>InfraSight AI <span>Shared foundation · Built for a three-person team</span></footer></div></main></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
